#!/usr/bin/env python3
"""
ProposalGen - Lotus Root Opportunity Analyzer

Analyze lotus-root product opportunities from a structured restaurant menu.
The script reads the menu JSON generated by restaurant_menu_analyzer.py, calls
an OpenAI-compatible text model, and writes JSON + Markdown opportunity reports.

Usage:
    python3 proposalGen/lotus_root_opportunity_analyzer.py <structured_menu.json>

Examples:
    python3 proposalGen/lotus_root_opportunity_analyzer.py \
        projects/menu_research/费大厨_20260527_095043/structured_menu.json

    python3 proposalGen/lotus_root_opportunity_analyzer.py \
        projects/menu_research/费大厨_20260527_095043/structured_menu.json \
        -o projects/menu_research/费大厨_20260527_095043

Dependencies:
    requests

Environment:
    OPENAI_API_KEY     required
    OPENAI_TEXT_MODEL  required unless --model is provided
    OPENAI_BASE_URL    optional, defaults to https://api.openai.com/v1
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

import requests

_REPO_ROOT = Path(__file__).resolve().parent.parent
_PPT_SCRIPTS_DIR = _REPO_ROOT / "skills" / "ppt-master" / "scripts"
if str(_PPT_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_PPT_SCRIPTS_DIR))

from config import load_prefixed_env_file  # noqa: E402


PRICE_RE = re.compile(
    r"(?:￥|¥|RMB\s*)\s*\d+(?:\.\d+)?|"
    r"\d+(?:\.\d+)?\s*(?:元|块|rmb|RMB|港元|HKD|HK\$)"
)

LOTUS_REFERENCE_ITEMS = [
    "藕合",
    "藕带",
    "干锅藕片",
    "筒骨莲藕汤",
    "凉拌藕丁",
    "桂花糯米藕",
    "酸辣藕尖",
    "擂椒藕丁",
    "藕泥蒸排骨",
    "莲藕小炒肉",
]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Analyze lotus-root opportunities from a structured menu.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "menu_json",
        help="Path to structured_menu.json generated by restaurant_menu_analyzer.py.",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        default="",
        help="Output directory. Defaults to the input menu directory.",
    )
    parser.add_argument(
        "--model",
        default="",
        help="Override OPENAI_TEXT_MODEL from .env.",
    )
    parser.add_argument(
        "--base-url",
        default="",
        help="Override OPENAI_BASE_URL from .env.",
    )
    parser.add_argument(
        "--allow-estimated-prices",
        action="store_true",
        help=(
            "Allow the model to propose price ranges when the input menu lacks exact prices. "
            "Default: do not invent prices; use 待核实."
        ),
    )
    parser.add_argument(
        "--max-opportunities",
        type=int,
        default=18,
        help="Maximum opportunity rows to ask the model for. Default: 18.",
    )
    return parser


def _load_env() -> None:
    load_prefixed_env_file(("OPENAI_",))


def _make_chat_url(base_url: str) -> str:
    base = (base_url or "https://api.openai.com/v1").rstrip("/")
    if base.endswith("/chat/completions"):
        return base
    return f"{base}/chat/completions"


def _strip_json_fence(content: str) -> str:
    text = content.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        return text[start:end + 1]
    return text


def _extract_prices(text: str) -> list[str]:
    return [match.group(0).strip() for match in PRICE_RE.finditer(text or "")]


def _flatten_menu(menu: dict[str, Any]) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for category in menu.get("categories", []):
        category_name = category.get("name", "")
        for item in category.get("items", []):
            if not isinstance(item, dict):
                continue
            haystack = " ".join(
                [
                    str(item.get("name", "")),
                    str(item.get("description", "")),
                    str(item.get("flavor_profile", "")),
                    " ".join(map(str, item.get("ingredients", []))),
                    json.dumps(item.get("source_evidence", []), ensure_ascii=False),
                ]
            )
            items.append({
                "category": item.get("category") or category_name,
                "name": item.get("name", ""),
                "description": item.get("description", ""),
                "ingredients": item.get("ingredients", []),
                "flavor_profile": item.get("flavor_profile", ""),
                "confidence": item.get("confidence", ""),
                "source_evidence": item.get("source_evidence", []),
                "prices_found_in_input": _extract_prices(haystack),
            })
    return items


def _build_payload(
    menu: dict[str, Any],
    input_path: Path,
    allow_estimated_prices: bool,
    max_opportunities: int,
) -> dict[str, Any]:
    restaurant = menu.get("restaurant") or input_path.parent.name
    menu_items = _flatten_menu(menu)
    existing_lotus_items = [
        item for item in menu_items
        if "藕" in item.get("name", "") or any("藕" in str(x) for x in item.get("ingredients", []))
    ]
    substitution_targets = [
        item for item in menu_items
        if any(
            token in " ".join([
                item.get("name", ""),
                item.get("description", ""),
                " ".join(map(str, item.get("ingredients", []))),
            ])
            for token in ("茄子", "芋", "土豆", "冬瓜", "丝瓜", "笋", "白菜", "豆腐", "排骨", "汤")
        )
    ]
    return {
        "restaurant": restaurant,
        "input_menu_path": str(input_path),
        "price_policy": (
            "允许给建议价格区间，但必须标注为建议价/待门店确认。"
            if allow_estimated_prices
            else "不要编造价格。输入中没有明确价格时，price 写“待核实”。"
        ),
        "max_opportunities": max(1, max_opportunities),
        "lotus_reference_items": LOTUS_REFERENCE_ITEMS,
        "existing_lotus_items": existing_lotus_items,
        "high_priority_substitution_targets": substitution_targets,
        "all_menu_items": menu_items,
    }


def _call_model(
    payload: dict[str, Any],
    *,
    model: str,
    base_url: str,
) -> dict[str, Any]:
    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set. Add it to .env or the current environment.")
    if not model:
        raise RuntimeError("OPENAI_TEXT_MODEL is not set. Add it to .env or pass --model.")

    output_schema = {
        "restaurant": payload["restaurant"],
        "input_menu_path": payload["input_menu_path"],
        "price_policy": payload["price_policy"],
        "summary": "莲藕机会总体判断，3-5句话",
        "opportunities": [
            {
                "name": "菜品名称",
                "opportunity_type": "existing_lotus|ingredient_substitution|new_lotus_item",
                "base_menu_item": "对应原菜单菜品；新菜填空字符串",
                "menu_section": "建议放入菜单分类",
                "price": "明确价格/建议价区间/待核实",
                "price_basis": "价格来源或为何待核实",
                "method_brief": "做法简介，50-120字",
                "lotus_role": "莲藕/藕带/藕泥在菜里的作用",
                "fit_reason": "为什么适合这家餐厅和现有菜单",
                "operational_notes": "备料、出餐、季节性或风险",
                "confidence": "high|medium|low",
            }
        ],
        "top_recommendations": ["最值得优先测试的3-5个菜品名"],
        "pricing_gaps": ["缺少价格依据的说明"],
    }

    messages = [
        {
            "role": "system",
            "content": (
                "你是餐饮菜单研发与品类机会分析顾问。"
                "你只能基于输入的结构化菜单和常识性烹饪知识提出莲藕机会，"
                "不要声称这些新菜已经在餐厅售卖。"
                "价格必须遵守输入中的 price_policy。"
                "输出必须是严格 JSON。"
            ),
        },
        {
            "role": "user",
            "content": (
                "请诊断该餐厅菜单里的莲藕相关机会。重点包括："
                "1) 已有菜单中直接含莲藕/藕/藕带的菜；"
                "2) 可用莲藕替换或改造的原菜，例如皮蛋青椒擂茄子的茄子换成藕丁，"
                "香芋/芋泥类改成藕泥，排骨/汤类改成莲藕排骨汤；"
                "3) 适合补充的莲藕菜，包括但不限于藕合、藕带、干锅藕片、筒骨莲藕汤、"
                "凉拌藕丁、桂花糯米藕。"
                "请列出菜品名称、价格、做法简介，并补充机会类型、适配理由、操作注意事项。"
                "不要把推测菜写成已售卖菜。\n\n"
                f"输出结构参考：{json.dumps(output_schema, ensure_ascii=False)}\n\n"
                f"输入材料：{json.dumps(payload, ensure_ascii=False)}"
            ),
        },
    ]

    request_body = {
        "model": model,
        "messages": messages,
        "temperature": 0.2,
        "response_format": {"type": "json_object"},
    }
    response = requests.post(
        _make_chat_url(base_url),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json=request_body,
        timeout=180,
    )
    if response.status_code >= 400 and "response_format" in response.text:
        request_body.pop("response_format", None)
        response = requests.post(
            _make_chat_url(base_url),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=request_body,
            timeout=180,
        )
    if response.status_code >= 400:
        raise RuntimeError(f"Model request failed ({response.status_code}): {response.text[:1000]}")

    data = response.json()
    content = data["choices"][0]["message"]["content"]
    return json.loads(_strip_json_fence(content))


def _write_markdown(report: dict[str, Any], output_path: Path) -> None:
    lines = [
        f"# {report.get('restaurant', '餐厅')} 莲藕相关机会诊断",
        "",
        str(report.get("summary", "")).strip(),
        "",
        f"价格规则：{report.get('price_policy', '')}",
        "",
        "## 机会清单",
        "",
        "| 菜品名称 | 类型 | 对应原菜 | 价格 | 做法简介 | 置信度 |",
        "|---|---|---|---|---|---|",
    ]
    for item in report.get("opportunities", []):
        lines.append(
            "| {name} | {otype} | {base} | {price} | {method} | {confidence} |".format(
                name=_escape_table(item.get("name", "")),
                otype=_escape_table(item.get("opportunity_type", "")),
                base=_escape_table(item.get("base_menu_item", "")),
                price=_escape_table(item.get("price", "")),
                method=_escape_table(item.get("method_brief", "")),
                confidence=_escape_table(item.get("confidence", "")),
            )
        )
    lines.extend(["", "## 重点推荐", ""])
    for name in report.get("top_recommendations", []):
        lines.append(f"- {name}")
    gaps = report.get("pricing_gaps", [])
    if gaps:
        lines.extend(["", "## 价格缺口", ""])
        for gap in gaps:
            lines.append(f"- {gap}")
    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _escape_table(value: Any) -> str:
    text = str(value or "").replace("\n", " ").strip()
    return text.replace("|", "\\|")


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    _load_env()

    input_path = Path(args.menu_json)
    if not input_path.exists():
        print(f"Input menu not found: {input_path}", file=sys.stderr)
        return 1
    output_dir = Path(args.output_dir) if args.output_dir else input_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        menu = json.loads(input_path.read_text(encoding="utf-8"))
        payload = _build_payload(
            menu,
            input_path=input_path,
            allow_estimated_prices=args.allow_estimated_prices,
            max_opportunities=args.max_opportunities,
        )
        report = _call_model(
            payload,
            model=args.model or os.environ.get("OPENAI_TEXT_MODEL", ""),
            base_url=args.base_url or os.environ.get("OPENAI_BASE_URL", ""),
        )
        json_path = output_dir / "lotus_root_opportunities.json"
        md_path = output_dir / "lotus_root_opportunities.md"
        json_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
        _write_markdown(report, md_path)
        print(json.dumps({
            "lotus_root_opportunities_json": str(json_path),
            "lotus_root_opportunities_md": str(md_path),
        }, ensure_ascii=False, indent=2))
        return 0
    except (json.JSONDecodeError, OSError, RuntimeError, requests.RequestException) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
